title: AIKIM
author: Junho Kim
email: arkimjh@kaist.ac.kr
description: > # this means to ignore newlines until "show_exerpts:"
  Hello, my name is Junho Kim, a Ph.D. student in Electrical Engineering at Korea Advanced Institute of Science and Technology.
  I am researching in Image and Video Systems Lab., under the supervision of Professor Yong Man Ro.
  I have experiences with mainly deep learning and machine learning.
  Now I am more focusing on visual-text and visual-audio multi-modal learning.
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: samarsault/plainwhite-jekyll
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Junho Kim
  tagline: Ph. D. Student
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: false # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.jpg" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    github: jhkim0911
    linkedIn: in/junhokim-kaist/
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    youtube: https://scholar.google.com/citations?user=ZxE16ZUAAAAJ&hl=en
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: arkimjh@kaist.ac.kr

    # Mastodon instances
#     mastodon:
#     - username: https://scholar.google.com/citations?user=ZxE16ZUAAAAJ&hl=en
#       instance: https://user-images.githubusercontent.com/4565568/29706177-1b3f8d24-8981-11e7-94dd-f561724011ab.png
#     - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: plainwhite


content:
#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: The Boring Company
#         link: boringcompany.com
#         # link_text: boringcompany.com
#         sub_title: Senior Network System Administrator
#         caption: November 2017 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ph.D. candidate
        caption: 2019 - present
        sub_title: Electrical Engineering
        quote: Korea Advanced Institute of Science and Technology
#       - layout: top-middle
# #         title:
#         caption: 2019 - 2020
#         sub_title: M.S. degree, Electrical Engineering
#         quote: Korea Advanced Institute of Science and Technology
      - layout: top-middle
#         title:
        caption: 2014 - 2019
        sub_title: B.S. degree, Electrical Engineering
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        quote: Korea Advanced Institute of Science and Technology # this will include new lines to allow paragraphs

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs

      <mark>International Journal</mark>
      - *Speech Reconstruction with Reminiscent Sound via Visual Voice Memory* <a href="https://ieeexplore.ieee.org/document/9618777" style="color: black;">[link]</a>

         **Joanna Hong**, Minsu Kim, Se Jin Park, Yong Man Ro

         IEEE/ACM Transactions on Audio, Speech, and Language Processing **(TASLP), 2021**

      - *Cromm-vsr: Cross-modal memory augmented visual speech recognition* <a href="https://ieeexplore.ieee.org/abstract/document/9566778" style="color: black;">[link]</a>

         Minsu Kim, **Joanna Hong**, Se Jin Park, Yong Man Ro

         IEEE Transactions on Multimedia **(TMM), 2021**

      <mark>International Conference</mark>
      - *SyncTalkFace: Talking Face Generation with Precise Lip-syncing via Audio-Lip Memory* <a href="https://www.aaai.org/AAAI22Papers/AAAI-7528.ParkS.pdf" style="color: black;">[link]</a>

         Se Jin Park, Minsu Kim, **Joanna Hong**, Jeongsoo Choi, and Yong Man Ro

         AAAI Conference on Artificial Intelligence **(AAAI), 2022 (Oral)**

      - *Lip to Speech Synthesis with Visual Context Attentional GAN* <a href="https://proceedings.neurips.cc/paper/2021/file/16437d40c29a1a7b1e78143c9c38f289-Paper.pdf" style="color: black;">[link]</a>

         Minsu Kim, **Joanna Hong**, Yong Man Ro

         Conference on Neural Information Processing Systems **(NeuIPS), 2021**

       - *Multi-Modality Associative Bridging Through Memory: Speech Sound Recollected From Face Video* <a href="https://openaccess.thecvf.com/content/ICCV2021/papers/Kim_Multi-Modality_Associative_Bridging_Through_Memory_Speech_Sound_Recollected_From_Face_ICCV_2021_paper.pdf" style="color: black;">[link]</a>

          Minsu Kim<span>&#42;</span>, **Joanna Hong<span>&#42;</span>**, Yong Man Ro **(<span>&#42;</span> equally contributed)**

          IEEE/CVF International Conference on Computer Vision **(ICCV), 2021**

        - *Unsupervised Disentangling of Viewpoint and Residues Variations by Substituting Representations for Robust Face Recognition* <a href="https://ieeexplore.ieee.org/document/9413039" style="color: black;">[link]</a>

          Minsu Kim, **Joanna Hong**, Junho Kim, Hong Joo Lee, and Yong Man Ro

          International Conference on Pattern Recognition **(ICPR), 2021**

        - *Comprehensive Facial Expression Synthesis Using Human-Interpretable Language* <a href="https://arxiv.org/abs/2007.08154" style="color: black;">[link]</a>

          **Joanna Hong**, Jung Uk Kim, Sangmin Lee, Yong Man Ro

          IEEE International Conference on Image Processing **(ICIP), 2020**

        - *Learning Style Correlation For Elaborate Few-Shot Classification* <a href="https://ieeexplore.ieee.org/document/9190685" style="color: black;">[link]</a>

          Junho Kim, Minsu Kim, Jung Uk Kim, Hong Joo Lee, Sangmin Lee, **Joanna Hong**, Yong Man Ro

          IEEE International Conference on Image Processing **(ICIP), 2020**

        - *Face Tells Detailed Expression: Generating Comprehensive Facial Expression Sentence Through Facial Action Units* <a href="https://dl.acm.org/doi/abs/10.1007/978-3-030-37734-2_9" style="color: black;">[link]</a>

          **Joanna Hong**, Hong Joo Lee, Yelin Kim, and Yong Man Ro

          International Conference on Multimedia Modeling **(MMM), 2020**


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AI World Cup 2018
        link: http://aiworldcup.org/
        # link_text: boringcompany.com
        sub_title: Organizing Committee
        caption: June 2018
#         quote: >
#           True 3D Smart Factory Solutions, Powered by Artificial Intelligence
        description: | # this will include new lines to allow paragraphs
          Emerging Industry 4.0 is rooted in various technologies, including IoT, big data, bio-chips, and AI. Among these technologies, AI technology is considered as the most powerful and influential technology with regard to Industry 4.0. The AI World Cup will be the proper venue for competition with AI technology. The scope of the AI World Cup competition covers AI soccer, AI commentator, and AI reporter.
      - layout: left
        title: Koh Young Technology, Inc.
        link: https://www.kohyoung.com/
        # link_text: boringcompany.com
        sub_title: Intern
        caption: September 2017 - February 2018
        quote: >
          True 3D Smart Factory Solutions, Powered by Artificial Intelligence
        description: | # this will include new lines to allow paragraphs
          Koh Young is a world leader in 3D measurement and inspection technology used in the production of electronic assemblies. Using patented Shadow-Free Moire’ 3D measurement technology, Koh Young provide best-in-class Solder Paste Inspection (SPI) and Automated Optical Inspection (AOI) for electronics manufacturers worldwide.
  - title: Patent # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: US/European/ Chinese/Korean Patent
#         link: https://www.kohyoung.com/
        # link_text: boringcompany.com
        sub_title: Duk Young Lee, Chan Woo Park, Tae Min Choi, <i>Joanna Hong</i>
        caption: <i>Koh Young Technology, Inc.</i>
#                  <br> 28 August 2019
        quote: >
          <b>"Apparatus and Method of Generating Control Parameter of Screen Printer"</b>
        description: | # this will include new lines to allow paragraphs
            The apparatus includes a memory that stores a simulation model configured to derive predictive inspection information on a printed state of solder paste based on a plurality of control parameters of the screen printer.
        #; a communication circuit configured to receive first inspection information on a plurality of solder pastes printed by the screen printer based on a first control parameter, and a processor electrically connected to the memory and the communication circuit.

  - title: Professional Activities
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Outstanding Teaching Assistant Award (2021)**

         Korea Advanced Institute of Science and Technology (KAIST)

      - **National Government Fellowship (2014 - Present)**
         Government of South Korea

  - title: Professional Activities
    layout: text
    content: | # this will include new lines to allow paragraphs

      <mark>Reviews</mark>
      - **Conference**

         European Conference on Machine Learning (2022)

         International Conference on Machine Learning (2021, 2022)

         Neural Information Processing Systems (2020, 2022(expected))

      <mark>Teaching</mark>
      - **EE474 Introduction to Multimedia, KAIST (2020, 2021, 2022)**
         Programming Lecturer & Teaching Assistant

      - **EE534 Pattern Recognition, KAIST (2021)**
         Teaching Assistant


plugins:
  - jekyll-seo-tag
#  - jekyll-feed
